---
- name: second playbook
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - passwords.yml
  
  tasks:
  - name: creating users
    user:
      name: "{{ item.name }}"
      comment: "{{ item.email }}"
      home: "{{ item.folder }}"
      password: "{{ item.password }}"
      state: present
      
      
    loop:
      - { name: 'Alice', email: 'alice@example.com', password: "{{ alicepass }}", folder: '/home/alice' } 
      - { name: 'Bob', email: 'bob@example.com', password: "{{ bobpass }}", folder: '/home/bob' } 
      - { name: 'Carol', email: 'carol@example.com', password: "{{ carolpass }}", folder: '/home/carol' }     
...